#!/usr/bin/env bash
#sed bir fayli acmadann uzerinde deyisilik aparir
[ "$EUID" -ne 0 ] && echo "Run as root!" && exit 1
sed -i '/127\.0\.0\.1\s\+localhost/c\127.0.0.2 localhost' /etc/hosts
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts
