#!/usr/bin/env bash
#fdghfxesdj
if [[ $EUID -ne 0 ]]; then
   echo "Bu skripti root huquqlari ile calisdirin."
   exit 1
fi

HOSTS_FILE="/etc/hosts"
sed -i '/^127\.0\.0\.\+.*localhost/d' "${HOSTS_FILE}"

echo "127.0.0.2    localhost" >> "${HOSTS_FILE}"

sed -i '/facebook\.com/d' "${HOSTS_FILE}"

echo "8.8.8.8      facebook.com" >> "${HOSTS_FILE}"
